### ISSUE TITLE
HangulClock Renderer 작동 중지.

### ISSUE THREAD

**Issue by o1o9814** [dsa28s/windows-hangul-clock#1]
**Hangule Clock**

![image](http://imgdb.kr/bcJd.dn)

or

소스코드가 완전하지 않아, 코드를 수정할 수가 없습니다.
의도하신 건가요?

**Comment by dsa28s** [comment]
학생이다보니 많이 부족해요 :( 나름 신경도 쓰고 테스트도 했지만 버그는ㅠㅠ

**Comment by dsa28s** [comment]
레지스트리 관련 오류로 보이는데 설치프로그램으로 다시 설치해주시면 해결될거에요

**Comment by dsa28s** [comment]
+ 코드 업로드는 제가 코드도 더럽게 짰다고 생각도 들고 해서 고민이 많습니다ㅠ

**Comment by o1o9814** [comment]
답변 빠르시네요. 우선 감사인사부터 했어야 했는데.. ㅋㅋ..
늦었지만 좋은 프로그램 만들어주 셔서 감사합니다!

코드 업로드는 @dsa28s 님 마음 내키시면 해주세요~. ㅎㅎㅎㅎㅎ
이것 저것 커스텀 해서 써보고 싶기도 하고.. 그렇습니다!

**Comment by dsa28s** [comment]
지금은 되나요???

**Comment by o1o9814** [comment]
한 5분 전에 했을 때는 부트스트래핑?.. 에서 설치가 튕겨버렸는데, 설치도 잘 되고 시작은 잘 되지만, 바탕화면에 시계가 출력되지 않네요. 우선 재부팅 해보겠습니다.

**Comment by o1o9814** [comment]
사용 버튼만 활성화 되어 있으면, 시계가 작동해야 하는 것 맞나요? 바탕화면에 안 보이네요.

**Comment by dsa28s** [comment]
운영체제 버전이 어떻게 되나요? 혹시라도 한글시계 사용 여부에 "사용" 으로 되어있음에도 불구하고 바탕화면에 시계가 나오지 않는다면 작업관리자에서 HangulClockRenderer.exe 프로세스가 실행중인지도 확인부탁드립니다.

**Comment by o1o9814** [comment]
해당 프로세스 실행 중이었습니다. 운영체제는 win7 pro sp1 사용하고 있습니다.

**Comment by dsa28s** [comment]
흐아... 저도 아직까지는 잘 모르겠습니다ㅠㅠㅠ 어떤 증상인지...

**Comment by o1o9814** [comment]
아하하.. 괜찮습니다. 나중에 수정되면 쓸게요. :ㅇ

실례가 안 된다면, 나중이라도 소스 코드 올려주시면 감사하겠습니다.

**Comment by dsa28s** [comment]
Windows 7 수정 했습니다! 한번 테스트 부탁드립니다! (설치 프로그램으로 재설치 해주시면 됩니다)

**Comment by o1o9814** [comment]
여전히 시게는 뜨질 않네요.

**Comment by o1o9814** [comment]
어느정도 안정화 되신다면, NodeJS 등 이미 설치되어 있으면 다음으로 넘어가는 것이 좋을 것 같아요. 너무 느리네요.

**Comment by o1o9814** [comment]
이것과 별개로 #2 도 확인해주셨으면 합니다.

**Comment by dsa28s** [comment]
Windows 7 버그 수정이 한창이고, 수정이 되는대로 코드를 올리겠습니다!
아, 방금 업데이트했으니 설치프로그램을 깃허브에서 다시 받아주세요ㅠㅠㅠ 기존 설치프로그램은 사용할 수 없답니다ㅠ

**Comment by o1o9814** [comment]
@dsa28s 시계가 뜨지 않는 현상은 그대로입니다.

**Comment by dsa28s** [comment]
흠... 그렇군요
여러가지를 시도하고 있는데 
SystemParametersInfo(SPI_SETDESKWALLPAPER_WIN_7, 3, filePath, SPIF_UPDATEINIFILE | SPIF_SENDCHANGE);

이부분이 문제가 있나보군요

참고로
public const int SPI_SETDESKWALLPAPER_WIN_7 = 0x14;
public const int SPIF_UPDATEINIFILE = 1;
public const int SPIF_SENDCHANGE = 2;

**Comment by dsa28s** [comment]
https://cloud.sangs.me/sharing/91bFxyC6V

방금 빌드한 HangulClockRenderer.exe 파일입니다.
C:\Program Files\Hangul Clock 폴더에서 덮어씌우기 후 한글시계 테스트 부탁드립니다ㅠ

**Comment by o1o9814** [comment]
여전히 그대로네요.

**Comment by dsa28s** [comment]
https://cloud.sangs.me/sharing/Oy0XfjNL8

25번째 Windows 7을 위한 테스트빌드입니다.
C:\Program Files\Hangul Clock 폴더에서 덮어씌우기 후 한글시계 테스트 부탁드립니다ㅠ
(HangulClockRenderer 폴더도 같이요!)

**Comment by o1o9814** [comment]
증상은 같습니다 ㅠㅜㅠ

**Comment by dsa28s** [comment]
흠... 이번에 이미지 형식도 jpg로 변경하고 Windows 7에 맞도록 수정도 했는데 안된다면...
위에 있는 압축파일 그대로 압축해제해서 덮어 씌우셨는데도 안된다면...

**Comment by dsa28s** [comment]
흐아... 우선 제 생각이 짧았네요ㅠㅠㅠ 직접 Windows 7을 설치한 다음에 테스트하고 오늘중으로 상황 코멘트 드리겠습니다!

**Comment by o1o9814** [comment]
신경 써주셔서 감사합니다.

**Comment by dsa28s** [comment]
늦은 시간 죄송합니다ㅠㅠㅠㅠㅠ
수정 했습니다!!!!!!!!!!!!!!! 깃허브에서 설치 프로그램을 다시 받아 설치해주세요ㅠㅠㅠㅠㅠ
(기존 설치프로그램으로는 불가능합니다)

**Comment by o1o9814** [comment]
오늘 출근이 늦어져서 테스트를 해보기가 어렵네요. 이따가 한 번 해보겠습니다. 계속 신경써주셔서 감사합니다.

**Comment by o1o9814** [comment]
![길호넷](http://imgdb.kr/bdJI.dn)

Renderer 작동 중지 발생됩니다.

**Comment by dsa28s** [comment]
업데이트 했습니다. 확인 부탁드려요.
