### ISSUE TITLE
Alt + Tab시 비어있는 윈도우 표시 문제

### ISSUE THREAD

**Issue by 009342** [dsa28s/windows-hangul-clock#13]
![image](https://user-images.githubusercontent.com/33230104/47804675-c1151b00-dd78-11e8-8668-5210c930737e.png)

Alt + Tab시 윈도우 리스트에 비어있는 윈도우가 표시됩니다.

MSDN에 올라온 WPF에서의 Alt + Tab시 윈도우가 뜨지 않게 해 주는 해결법을 첨부합니다.

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/9c4ada92-5065-4abb-a295-d62e5ddaf2b1/wpf-window-is-showen-in-alttab-list-though-windowstylenone-showintaskbarfalse?forum=wpf

도움이 되셨으면 좋겠네요 :)

**Comment by dsa28s** [comment]
감사합니다!!
해당 버그는 베타2 에서 해결하도록 하겠습니다.
