### ISSUE TITLE
윈도우10 삭제가 안됩니다 

### ISSUE THREAD

**Issue by SongJinBeom** [dsa28s/windows-hangul-clock#14]
제꺼만 이상한지 모르겠는데
프로그램 추가/제거에서
제거를 하면 한글시계 제거 프로그램을 실행할 수 없습니다 라고 나옵니다

**Comment by dsa28s** [comment]
해당 버그는 인지 후 다음 버전에서 업데이트 하려고 합니다ㅠㅠ

**Comment by dsa28s** [comment]
**한글시계를 재설치 하신 후, 프로그램 추가/제거 에서 제거하시면 이제 정상적으로 제거하실 수 있어요!**
불편을 드려 죄송합니다ㅠㅠ
