### ISSUE TITLE
사용 체크 후 바탕화면 이미지 변경 시 작동 중지

### ISSUE THREAD

**Issue by o1o9814** [dsa28s/windows-hangul-clock#2]
![길호넷](http://imgdb.kr/bcXO.dn)

운영체제 : Window 7 pro sp1 (64bit)

**Comment by o1o9814** [comment]
설치 직후엔 작동 중지 떳었는데, 재실행 시키고 나서는 화면 바꾸어도 중지되진 않네요.

**Comment by o1o9814** [comment]
여전히 시계는 안 뜹니다.

**Comment by dsa28s** [comment]
아이고... Windows 7에서 배경화면 관련 공부를 좀 더 해야겠습니다ㅠ
