### ISSUE TITLE
두번째 모니터에서 적용하면 화면이 꽉채워지지 않습니다.

### ISSUE THREAD

**Issue by bleetoteelb** [dsa28s/windows-hangul-clock#20]
Windows 버전 : Windows 10 Enterprise x64비트 운영체제
모니터 정보 : (왼쪽부터 차례대로)
디스플레이 2 (1920x1080, 100% 비율)
디스플레이 1 (2560x1440, 125% 비율)

1번 모니터(주모니터)는 정상적으로 시계가 뜨고 사진도 화면을 꽉채우는데,
2번 모니터(디스플레이2)에서는 한글시계를 적용하면 사진이 작아지면서 왼쪽위로 정렬이 되고 나머지부분은 검은색으로 바뀝니다. 한마디로 사진이 화면을 꽉채우지 않습니다.

제 디스플레이 설정을 변경해야 하는건가요?

**Comment by dsa28s** [comment]
혹시 자세한 스크린샷도 같이 첨부해주실 수 있으신가요??

**Comment by bleetoteelb** [comment]
![han_error](https://user-images.githubusercontent.com/26691943/54397260-3c101a00-46f9-11e9-8447-850d0b206a5f.JPG)
![han_not_error](https://user-images.githubusercontent.com/26691943/54397267-40d4ce00-46f9-11e9-93b9-d9fce1a85101.JPG)

그리고 모니터정보 정정합니다.
두 모니터의 해상도가 동일합니다!

모니터 정보 : (왼쪽부터 차례대로)
디스플레이 2 (1920x1080, 100% 비율)
디스플레이 1 (1920x1080, 125% 비율)

**Comment by CraftyDragon678** [comment]
https://stackoverflow.com/questions/53012896/using-setwindowpos-with-multiple-monitors 여기에 해결방안이 있는것 같습니다. 
원인은 PrimaryScreen.Bound.X, Y 모두 0, 0으로 되는 것 때문입니다.

**Comment by dsa28s** [comment]
@CraftyDragon678 해당 문제를 파악했으며, 제가 시간이 될 때에 수정해서 베타2로 올리도록 하겠습니다ㅜㅜ (아니면 PR도 조심스럽게 요청해봅니다...ㅎ)

**Comment by CraftyDragon678** [comment]
몇번 테스트 해봤는데 parent가 workerw라서 그런 것 같기도 하네요. 그냥 일반 윈도우(WPF)를 만들어 봤는데 그건 모서리에 맞게 잘 가는 것 같더라고요.

**Comment by CraftyDragon678** [comment]
![image](https://user-images.githubusercontent.com/25890954/71728392-4e259980-2e80-11ea-9742-2993e182ee96.png)
P : 3840 x 2160
S : 1920 x 1080
