### ISSUE TITLE
Readme에 스크린샷이 안보여요.

### ISSUE THREAD

**Issue by junsooo** [dsa28s/windows-hangul-clock#21]
Readme에 스크린샷이 안보입니다.

https://raw.githubusercontent.com/dsa28s/windows-hangul-clock/master/Screenshot/shot6.PNG <br>
404: Not Found 라고 뜨네요.

**Comment by dsa28s** [comment]
앗, 해결하도록 하겠습니다ㅠㅠ 감사합니다ㅠㅠ
