### ISSUE TITLE
왼쪽으로 문구를 이동하면 짤림현상

### ISSUE THREAD

**Issue by j1ngj1ng** [dsa28s/windows-hangul-clock#22]
위, 아래, 오른쪽에서는 축소되어 있는 문구가 왼쪽으로 설정하면 글자가 커지면서 짤리는 현상이 발생합니다.
![image](https://user-images.githubusercontent.com/41906465/57524351-83fe9680-7362-11e9-93ae-799051f60804.png)

![image](https://user-images.githubusercontent.com/41906465/57524408-ac869080-7362-11e9-8e93-65232b84e051.png)

**Comment by dsa28s** [comment]
해당 이슈는 **한글시계 베타 2** 에서 해결될 예정입니다ㅠ
버그 제보 감사합니다!
