### ISSUE TITLE
한글시계 삭제

### ISSUE THREAD

**Issue by hoyo123** [dsa28s/windows-hangul-clock#24]
안녕하세요. 한글시계를 잘 사용하고 있는 유저입니다! 다름이 아니라 제가 제 노트북에 깔려있는 한글시계를 지우고싶은데요, 제어판에서는 제거할 수 없다고 그러고 c/programs/han 암튼 이 경로로 가서 삭제를 하면 폴더가 다른데에서 열려있어서 못지운대요. 분명 한글시계 사용 안함으로 해놓고 다시시작도 계속 해봤는데 자꾸 다른데에서 열려있다네요; 어떻게 지우죠?

**Comment by CraftyDragon678** [comment]
Duplicate of #14

**Comment by dsa28s** [comment]
@CraftyDragon678 님 이슈 링크 감사합니다!!
해당 부분은 베타 2에서 해결될 예정이에요ㅠㅠ

일단 임시방편으로 해결 방안을 알려드립니다.

1. 시작 > 실행 (윈도우키 + R) 에서 아래의 명령어 2줄을 각각 입력 후, 엔터를 눌러주세요.
`taskkill /f /im HangulClockMonitoringProcess.exe`
`taskkill /f /im HangulClockRenderer.exe`

2. C:\Program Files\Hangul Clock 폴더를 통째로 지워주시면 됩니다.

불편을 드려 죄송합니다ㅠㅠ

**Comment by dsa28s** [comment]
해당 이슈는 @CraftyDragon678 님께서 언급해주신 #14 번 이슈와 중복이므로, 클로즈 하고, #14 번 이슈에서 업데이트 하도록 하겠습니다.

**Comment by jimin1231** [comment]
1의 방법은 성공했는데 2의 방법에서 다른 프로그램이 실행되고 있다고 삭제되지 않습니다ㅠㅠ..

**Comment by CraftyDragon678** [comment]
> 
> 
> 1의 방법은 성공했는데 2의 방법에서 다른 프로그램이 실행되고 있다고 삭제되지 않습니다ㅠㅠ..

시작 > 실행 말고 cmd에서 저 명령어를 입력 했을 때 성공적으로 실행 되나요??
