### ISSUE TITLE
4K 모니터에서의 시계 문제

### ISSUE THREAD

**Issue by newMocha** [dsa28s/windows-hangul-clock#25]
4K 모니터에서 배율 설정이 제대로 적용되지 않아 발생하는 문제로 추정됩니다.
![image](https://user-images.githubusercontent.com/47000640/63348692-bf165a00-c394-11e9-8bd9-d665cd869fe8.png)
배율 변경 시에는 제대로 작동합니다.
![image](https://user-images.githubusercontent.com/47000640/63348795-fbe25100-c394-11e9-85b2-59f54718c90e.png)

**Comment by CraftyDragon678** [comment]
#20 과 비슷한 이슈 같네요. 여기도 DPI관련 이슈가 있는 것 같습니다.

**Comment by dsa28s** [comment]
윈도우에서 배율 처리가 좀 어렵네요ㅠㅠ
배율이랑 멀티디스플레이를 사용할 경우, 좌표계가 변경되어서 처리하기도 까다롭구요ㅠㅠ

제보 감사합니다ㅠ

**Comment by GeniusMocha** [comment]
멀티 디스플레이는 사용하지 않고, 단일 모니터로 사용중입니다.
해상도에 상관 없이 배율 적용(100% 이상)시 문제가 생기는 것으로 보이며, 100%에서 배율이 점차 커지면 커질수록 시계 영역이 점점 작아집니다.

- 125%
![image](https://user-images.githubusercontent.com/47000640/63353913-795e8f00-c39e-11e9-8576-dd24b4d9c491.png)

- 150%
![image](https://user-images.githubusercontent.com/47000640/63353952-8d09f580-c39e-11e9-8901-5939edf1764f.png)

- 175%
![image](https://user-images.githubusercontent.com/47000640/63353976-972bf400-c39e-11e9-8bba-3090ac7b7b8c.png)

각 배율당 캡쳐본도 드리는 게 참고에 좋을 듯 해서 캡쳐 해 드립니다.
듀얼 스크린에 제한된 경우가 아닌 배율의 문제가 큰 듯 합니다.

**Comment by dsa28s** [comment]
혹시 사용중인 윈도우 빌드버전을 알 수 있을까요??
(예 : Windows 10 빌드 1903)

**Comment by GeniusMocha** [comment]
윈도우 빌드버전은 1903(18362.295) 사용중입니다.

**Comment by newMocha** [comment]
오류 수정 감사합니다.
