### ISSUE TITLE
한글시계 제거가 안되네요 

### ISSUE THREAD

**Issue by sungle3737** [dsa28s/windows-hangul-clock#28]
### 모니터를 여러개 사용중인데 아예 작동을 안해서 지우려는데 지워지지도 않네요!
---
![image](https://user-images.githubusercontent.com/27716524/66270404-28432580-e88e-11e9-94b8-f048b5343c3b.png)

**Comment by CraftyDragon678** [comment]
Dup with #11

**Comment by CraftyDragon678** [comment]
#24 에 임시적인 해결방안이 있습니다
