### ISSUE TITLE
시계가 삭제가 되지도 않고 다른파일들도 삭제가 되지 않습니다....

### ISSUE THREAD

**Issue by KangDaeWoong** [dsa28s/windows-hangul-clock#29]
시계를 설치하고 다른파일을 삭제하려고 하니 삭제되지 않네요......................시계도 삭제가 안되고요....제작자께서 알려주신 방법을 사용했는데 삭제가 되지 않습니다....시계가 삭제되지 않아도 좋습니다. 다른파일을 삭제하게만 해주세요.

**Comment by CraftyDragon678** [comment]
어떤 오류로 삭제가 안 되나요?

**Comment by dladladbwls** [comment]
저도 안되어서 찾아보고 있는데 .. Hangul Clock 폴더 속에 있는 몇몇개의 파일들과 3.0베타 1 앱도 삭제가 안돼요 .. 어떻게 하죠 .. 찝찝하네요 ㅠㅠ

**Comment by dsa28s** [comment]
원인을 파악했고, 곧 수정될 이슈에요ㅠㅠ 
불편을 드려 죄송하고, 제거 프로그램 이슈 해결하면, 해당 이슈에 다시 댓글로 알려드리겠습니다ㅜㅜ

**Comment by dsa28s** [comment]
한글시계를 재설치 하신 후, 프로그램 추가/제거 에서 제거하시면 이제 정상적으로 제거하실 수 있어요!
불편을 드려 죄송합니다ㅠㅠ
