### ISSUE TITLE
한글시계 윈도우 버전 삭제방법 문의

### ISSUE THREAD

**Issue by Lattecom** [dsa28s/windows-hangul-clock#3]
안녕하세요. 우선 한글시계 개발해주셔서 감사합니다. 

맥용 한글시계를 먼저 접하게 되고 윈도우버전도 설치하게 되었습니다.
프로그램 컨셉, 기능 자체는 매우 만족스러우나 프로그램 실행 및 설정하는 과정이 좀 번거로워 부득이하게 윈도우에선 삭제하려합니다. 
자세히는 모르겠으나 설치시에 여러 다른 패키지들을 사용한걸로 알고 있는데 별도의 언인스톨러나 깔끔하게 삭제하는 방법을 알고 싶습니다.
참고로 프로그램 추가/제거 에서는 한글시계가 표시되지 않고 있습니다. 처음엔 있었으나 프로그램 추가/제거에서 제거를 했을 때는 이미 없다고 나오고 리스트에서 삭제되었습니다. 아마 중간에 업데이트를 진행하면서 앱UI 등이 크게 바뀌었는데 업데이트 이전 버전에 해당된 것으로 생각합니다. 

아래는 추후 개발에 도움이 되실까하고 개인적으로 불편하다고 생각한 부분에 대해 설명해 보았습니다. 혹시 제가 잘못 설정해서 사용하고 있었던 부분이 있으면 알려주시면 지적해주셔도 좋습니다.
매번 부팅시 자동실행 되는데 매번 실행 확인을 눌러줘야하고, 확인했을 때 커맨드창이 떠서 설정하는 것과 앱화면이 뜬후 설정 시간 등이 부팅 시마다 겪다보니 많이 번거로웠습니다. 
또 부팅 시에 실행 취소를 눌러도 커맨드창은 여전히 무언가 진행하며 에러 화면 같은걸 띄웠는데 이 또한 사용자경험 측면에서 좋지 못했습니다.

뭔가 불평만하고 삭제방법을 알려달라고 남기는게 개발자분에게 실례가 되지 않을까 조심스럽네요 ㅠ
다시한번 한글시계 개발해주셔서 감사하단 인사드립니다. 맥버전은 여전히 잘 쓰고 있습니다. :-)

**Comment by dsa28s** [comment]
우선 사용에 불편을 드려 죄송합니다ㅠㅠㅠ
한글시계 제거는 C:\Program Files\Hangul Clock 폴더를 통째로 지워주시면 말끔이 지워집니다.
아, 또 의존성으로는 node.js 를 사용하는데, 혹시라도 node.js 를 사용하신다면 상관없지만 사용하시지 않는다면 지워주세요.

아직 학생신분이고 고3인지라 시간적 여유가 없고 업데이트를 못해드린 점에 죄송하다고 생각드려요ㅠㅠ
아마 다음 업데이트 땐 "부팅 시 관리자 권한 요청 제거" / "부팅 시 한글시계 설정 화면 나오는 현상 수정" 이 포함될것으로 보여요.

피드백 감사드립니다!

**Comment by Lattecom** [comment]
고맙습니다.  업데이트되면 다시 찾아올게요! :-)
