### ISSUE TITLE
setup파일은 삭제가 되는데 깃허브에서 코드를 받은 파일이 삭제가 안됩니다

### ISSUE THREAD

**Issue by LJM1231** [dsa28s/windows-hangul-clock#30]
#14 #24 에 있는 임시 방법을 사용해보아도 다른파일이 실행중이라고 삭제가 되지 않네요..ㅠㅠㅠ 코드파일은 지우고 setup파일만 남기고 싶습니다.

**Comment by jimin1231** [comment]
> #14 #24 에 있는 임시 방법을 사용해보아도 다른파일이 실행중이라고 삭제가 되지 않네요..ㅠㅠㅠ 코드파일은 지우고 setup파일만 남기고 싶습니다.

해결하였습니다! 글 지워주시면 감사하겠습니다

**Comment by CraftyDragon678** [comment]
해결되셨으면 Close issue를 눌러서 닫아주세요

**Comment by dsa28s** [comment]
**한글시계를 재설치 하신 후, 프로그램 추가/제거 에서 제거하시면 이제 정상적으로 제거하실 수 있어요!**
불편을 드려 죄송합니다ㅠㅠ
