### ISSUE TITLE
한글시계 버전 3 베타 2 업데이트 예정 안내

### ISSUE THREAD

**Issue by dsa28s** [dsa28s/windows-hangul-clock#32]
안녕하세요!

여태 베타 1 이후로 업데이트가 없어서 많이 실망하셨죠?ㅠㅠ 하도 일이 바빠서 요근래 신경을 쓰지 못하고 있었어요ㅜㅜ

## 다음 업데이트는 아래의 사항을 포함하여 업데이트 될 예정입니다!

- 한글시계 제거 불가 문제 (#14, #28, #29, #30)
- Alt + Tab 입력시, 비어있는 항목이 나오는 문제 (#13)
- 시계를 확대하면, 시계가 잘리는 문제 (#11)
- 유튜브 영상 링크 표시 문제 (#10)
- DPI 로 인한 시계 표시 문제 (#25)

## 다음 베타 3 신규 업데이트 예정
- [신규기능] 다른 유저가 작성한 문구를 한글시계 홈페이지, 한글시계에 표시하는 기능 (옵션에서 설정가능)
- 한글시계 홈페이지 리뉴얼 (아래 사진 참고)

![한글시계 랜딩 페이지](https://user-images.githubusercontent.com/10934461/71723358-b750e100-2e6f-11ea-990b-07e49e0f2257.png)

요근래 한글시계 Github 관리를 못했는데, @CraftyDragon678 님께서 저대신 댓글을 잘 달아주셔서(?) 정말 감사드려요ㅠ 
나머지 이슈는 차근차근 보는 중입니다ㅠ
곧 업데이트 소식으로 찾아뵙겠습니다!

**Comment by dsa28s** [comment]
추가적으로, 한글시계를 사용하면서 신규 기능 추가, 버그 발견 등이 있다면 여기 스레드 댓글 혹은 이슈로 등록 부탁드립니다!

**Comment by garamm0429** [comment]
안녕하세요 몇년째 시계 너무 잘 쓰고 는 사용자인데 작년?부터 계속 exe 파일을 실행하면 한 5초 정도 켜져 있다가 자동으로 종료가 돼요ㅠㅠ 시계 자체는 노트북 화면에 잘 떠있는데 에러가 뜨는 건지 가끔 배경화면과 함께 사라져서 배경이 까맣게 되고 너무 바로 종료되니까 문구나 시계 크기를 조정하고 싶어도 할 수가 없네요...
