### ISSUE TITLE
윈도우10에서 바탕화면 문제

### ISSUE THREAD

**Issue by doyunique** [dsa28s/windows-hangul-clock#35]
1. 한글시계를 실행하면 바탕화면에 있는 아이콘들이 다 안 보입니다.. 그냥 가운데 한글시계만 덩그러니 있어요ㅜㅜ

2. 윈도우즈 바탕화면을 슬라이드쇼로 설정해두고 여러가지 바탕화면이 랜덤하게 바뀌도록 설정해두었는데, 한글시계를 실행하면 실행됐을 때의 바탕화면으로 계속 고정됩니다.

아무리 봐도 프로그램 안에 이런 부분에 대한 설정을 할 수 있는 곳이 없어서요..(당연히 배경화면 고정이미지는 사용안함 상태 확인했습니다)

인터넷 찾아보니 제 PC에서만 이러는 것 같은데 혹시 한글시계를 제대로 사용하기 위해 윈도우 설정을 따로 해야 하나요..? 제가 프로그램을 원활하게 사용할 수 있도록 도와주세요. 감사합니다.

**Comment by CraftyDragon678** [comment]
1. 스크린샷이 있다면 원인을 파악하기 쉬울 것 같습니다.
2. 바탕화면 설정 탭에서 모든걸 체크 해제 하셨나요..? 만약 다 체크 해제 하신 거라면 제가 소스코드를 본지 좀 돼서 기억이 가물가물 한데 소스코드에 사용중인 바탕화면을 불러와서 같이 바탕화면 렌더링을 하는 걸로 기억합니다. 이 부분이 수정 되면 아마 될 것 같습니다..

**Comment by doyunique** [comment]
스크린샷 첨부할게요.. 스크린샷 따다 보니까 한글시계가 화면보호기처럼? 아예 화면을 덮고있는 상황인 거 같은데... 이거 어떻게 해야 되죠;

이 상태로 아예 바탕화면을 사용할 수가 없게 돼요..
![3](https://user-images.githubusercontent.com/62066739/76585149-0034ae00-6521-11ea-83ed-cfe87ab65b2c.png)
![4](https://user-images.githubusercontent.com/62066739/76585133-f8750980-6520-11ea-874a-5411f08d2439.png)
![2](https://user-images.githubusercontent.com/62066739/76585191-1e021300-6521-11ea-9338-60190469435b.png)

제가 어떻게 해야 할까요? 미리 감사드립니당

**Comment by doyunique** [comment]
왠지 모르겠는데 오늘 갑자기 제대로 뜨네요..? alt+tab 에서 빈 윈도우 뜨는 오류는 있지만 다른건 다 멀쩡하게 돼요... 어떻게 된 건지 영 모르겠지만 여튼 해결됐습니다
