### ISSUE TITLE
윈10 한글시계 Bootstrapper 작동 중지 문제

### ISSUE THREAD

**Issue by N41rn5** [dsa28s/windows-hangul-clock#4]
안녕하세요! 페이스북에서 프로그램 보고 이뻐서 설치하게되었습니다!
좋은 프로그램 만들어주셔서 감사합니다 ㅎㅎ

현재 Microsoft Windows 10 Home edition ( x64 ) / 버젼 - 10.0.15063 사용중입니다.
처음 한글시계 setup파일 실행시 "한글시계 설치" 단계에서 계속해서 Bootstrapper 작동 중지 오류가 발생하였습니다! 그래서 혹시나 구 버전의 Node.js가 설치되어 있는 것이 문제인가 싶어 node.js를 삭제, Hangul Clock 폴더 삭제 후 재부팅 및 설치를 진행하였더니 정상적으로 설치되었습니다.

혹시나 시간적 여유가 되신다면 해당 오류가 이미 설치된 Node.js로 인한 것인지 한번만 확인 해 주시면 감사하겠습니다 ㅎㅎ

한글시계 만들어주셔서 감사하고 잘 쓰도록 하겠습니다! 감사합니다!

**Comment by dsa28s** [comment]
앗, 버그 제보 감사드립니다ㅠㅠㅠㅠ 원인 파악 후에 수정하겠습니다!! 감사합니다 :)

**Comment by kpjhg0124** [comment]
저도 같은 현상이 발생합니다. ;^;
관련이 있는지는 모르겠으나, 저 역시 Node.js(더 나아가 Bitnami wamp 스택이 돌아가고 있습니다.)가 백그라운드에 상주한 상태입니다.
두차례 프로그램이 중단되네요.

환경은 Windows 10 (x64) 15063 사용중입니다.

**Comment by dsa28s** [comment]
해당 버그는 버전 3의 설치 프로그램부터 해결되었습니당!
