### ISSUE TITLE
홈페이지 인터넷익스플로러 지원 문제

### ISSUE THREAD

**Issue by jureaky** [dsa28s/windows-hangul-clock#6]
안녕하세요!

한글시계 너무 이쁜 것 같아요 잘 쓰고 있습니다 !

그런데 홈페이지가 인터넷 익스플로러에서 접속하면 버튼이 활성화가 안되는 문제가 있어서

이슈 올려드려요

저는 익스플로러11버전으로 접속했습니다.

한번 확인해 주세요 !

**Comment by dsa28s** [comment]
해당 문제도 해결했는데, 이슈를 지금 봤네요ㅠㅠ 죄송합니당ㅠ
