### ISSUE TITLE
현재 시간과 맞지 않는 문제

### ISSUE THREAD

**Issue by SkyLightQP** [dsa28s/windows-hangul-clock#7]
한글시계를 쓰다보니 실제 시간보다 1분 정도 느리게 표시가 됩니다.
새로고침 간격 때문에 이런 문제가 발생하는거 같은데 
다음 업데이트 때 수정이 가능할까요?

**Comment by dsa28s** [comment]
오늘 배포된 버전 3에서 해결했습니다 :)
